# Generated by Django 2.2.2 on 2019-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
